import SNETAudioUpload from "./index";

export const DefaultAudioUpload = {
    args: {
        width: '500px',
        tabHeight: 300,
        imageName: 'Sample Image',
        disableUploadTab: false,
        disableUrlTab: false,
        disableResetButton: false,
        returnByteArray: false,
        outputFormat: 'image/png',
        allowedInputTypes: ['image/png', 'image/jpeg', 'image/jpg'],
        maxImageSize: 10000000,
        maxImageWidth: "500px",
        maxImageHeight: "500px",
        displayProportionalImage: true,
        allowURL: true,
        instantUrlFetch: false,
        imageGallery: [],
        galleryCols: 3,
        infoTip: 'This is a tooltip with some information.',
        mainColor: { main: "#0000FF" }, 
        displayModeTitle: 'Result',
        outputImage: '',
        outputImageName: 'service-output',
        disableInputTab: false,
        disableOutputTab: false,
        disableComparisonTab: false,
        disableDownloadButton: false,
        overlayInputImage: true,
        inputTabTitle: 'Input',
        outputTabTitle: 'Output',
        comparisonTabTitle: 'Comparison',
        imageDataFunc: ()=>{},
        outputImageMimeType: "image/png",
    },
};

export default {
    title: 'Components/SNETAudioUpload',
    component: SNETAudioUpload,
    tags: ['autodocs'],
    argTypes: {
        width: { control: 'text' },
        tabHeight: { control: 'number' },
        imageName: { control: 'text' },
        disableUploadTab: { control: 'boolean' },
        disableUrlTab: { control: 'boolean' },
        disableResetButton: { control: 'boolean' },
        returnByteArray: { control: 'boolean' },
        outputFormat: {
            control: 'radio',
            options: ['image/png', 'image/jpg', 'image/jpeg'],
        },
        allowedInputTypes: { control: 'array' },
        maxImageSize: { control: 'number' },
        displayProportionalImage: { control: 'boolean' },
        allowURL: { control: 'boolean' },
        instantUrlFetch: { control: 'boolean' },
        imageGallery: { control: 'array' },
        galleryCols: { control: 'number' },
        infoTip: { control: 'text' },
        mainColor: { control: 'color' },
        displayModeTitle: { control: 'text' },
        outputImage: { control: 'text' },
        outputImageMimeType: {
            control: 'radio',
            options: [
                'application/octet-stream',
                'image/png',
                'image/jpg',
                'image/jpeg',
                'image/gif',
            ],
        },
        outputImageName: { control: 'text' },
        disableInputTab: { control: 'boolean' },
        disableOutputTab: { control: 'boolean' },
        disableComparisonTab: { control: 'boolean' },
        disableDownloadButton: { control: 'boolean' },
        overlayInputImage: { control: 'boolean' },
        inputTabTitle: { control: 'text' },
        outputTabTitle: { control: 'text' },
        comparisonTabTitle: { control: 'text' },
    },
};
